const Vdos = {
    'admiration': ["VZWOTFK0qVM"],
    'amusement': ["url3", "url4"],
    'anger': ["pEnpkJ2TPys", "efbEA8DAMqQ"],
    'annoyance': ["zbni46ENrLE", "S_92aPqdQ2w"],
    'approval': ["url3", "url4"],
    'caring': ["8G6ebWgaZdU", "url4"],
    'confusion': ["x584o_8jV8Q", "PVBEWa-w8Is"],
    'curiosity': ["url3", "url4"],
    'desire': ["dtBtov2f7e4", "nLBrPED52qw"],
    'disappointment': ["hBiiLqPP4VA", "8KgUFMN7aJQ"],
    'disapproval': ["YP6-s-u2WRQ", "lAkY4dBJXyo"],
    'disgust': ["MXqcCW7Fsmo", "iPXvm0fOE-0"],
    'embarrassment': ["9gIy8tShxTw", "e5e437OGTyQ"],
    'excitement': ["e1lGJnQNTNk", "agHrCwPaZqU"],
    'fear': ["VnxwioXNVls", "2JvZGNxpbWU"],
    'gratitude': ["79rcaufqLyg", "LG0COiQBjXA"],
    'grief': ["eEcaUhxAH2g", "IfDV103duCM"],
    'joy': ["78nsxRxbf4w", "S3bqeErBHTM"],
    'love': ["vMeEKBaiPbg", "f_OPjYQovAE"],
    'nervousness': ["xsEJ6GeAGb0", "nDmjP3P5M2c"],
    'optimism': ["MBRqu0YOH14", "FrqBWQ-mVEc"],
    'pride': ["W6eLkFr9yzE", "_cRIGLNff-c"],
    'realization': ["url3", "url4"],
    'relief': ["RKECKQWVlO4", "IHbbMF3ltcs"],
    'remorse': ["q-ApAdEOm5s", "Xk22l_qzVNc"],
    'sadness': ["IDPDEKtd2yM", "E5S3nw61ehc"],
    'surprise': ["url3", "url4"],
    'neutral': ["CItQU5TtMbs", "z5XdX_ryHoc", "o3Qb5ifII4o", "-UcNX1_Z0Fg" , "dX4fEmYqLrs", "Nu5m5r8GP1U", "-6_XHiRSMMQ"],
};

export {Vdos};